# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uoo2nJBvUlWWNHL_6-ejPjC4-odtFBeo
"""

import numpy as np
import cv2
import math
from matplotlib import pyplot as plt

# from google.colab.patches import cv2_imshow


# testarray
im1 = cv2.imread('prof pic.jpg')
windowname = 'image'
#cv2.imshow(im1)
cv2.imshow(windowname,im1)  #this should work but not in Colab
im1_show = cv2.cvtColor(im1, cv2.COLOR_BGR2RGB)
plt.figure()
plt.imshow(im1_show)

im2 = np.zeros((100, 200))
#cv2.imshow(im2)
windowname = 'image2'
cv2.imshow(windowname,im2) #this should work but not in Colab
plt.figure()
plt.imshow(im2, cmap='gray', vmin=0, vmax=255)

length, width = im2.shape
radius = 0.5 * min(length, width)
radius
for i in range(length):
    for j in range(width):
        if math.sqrt((i - length / 2) ** 2 + (j - width / 2) ** 2) > radius:
            im2[i, j] = 255

#cv2.imshow(im2)
windowname = 'image3'
cv2.imshow(windowname,im2) #this should work but not in Colab
#plt.figure()
#plt.imshow(im2, cmap='gray', vmin=0, vmax=255)
cv2.imwrite('./1_test2.jpg',im2)

# closing all open windows
#cv2.waitKey()
#cv2.destroyAllWindows()